services:
  - type: web
    name: turing-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DATABASE_URL
        fromDatabase:
          name: turing-db
          property: connectionString

databases:
  - name: turing-db