services:
  - type: web
    name: turing-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: 'django-insecure-q&now(w)bsjcwmk(zrfq-tvv!+(!k%a*g=amdyc%synqw2fric'
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: DATABASE_URL
        fromDatabase:
          name: turing-db
          property: connectionString

databases:
  - name: turing-db
